var mistype1 = {"2": ["Appeals to principles over personal feelings.", "Defend autonomy.", "Restrained in expression of positive feelings, but easier to express negative feelings."],
                "3": ["Idealists, striving for perfection. Efficient for the sake of reaching the desired standard.", "Attached to methods or procedures.", "Less able to conceal irritations and disappointments.", "Able to suppress feelings for the time being.", "“Listen to me—I know the right way to do things.” Offers themselves as examples of high standard."],
                "4": ["Attend to responsibilities first, feelings later. Would not allow self to “indulge” in feelings very long.", "Critical over others’ inefficiency or failures.", "Respond by pushing other party harder.", "This type, when stressed, looks like an unhealthy Type B—moody and irrational."],
                "5": ["More from the gut. Emphasis on certainty and judgment.", "More interested in using thoughts to relate more perfectly to themselves and the world.", "Judge from idealistic standards."],
                "6": ["Self-controlled, impersonal efficiency, orderliness, propriety.", "Compliant to demands of ideals.", "'Inner Critic' in the head.", "Guilty when doing something contrary to ideals."],
                "7": ["This type, when growing, looks like a healthy Type A—spontaneous and joyful.", "Hold high standards and expect to be disappointed.", "Know their mission.", "True perfectionism drives them to be angry and critique themselves.", "Rigid in plans, often focused. Quite self-conscious socially. Driven by anger."],
                "8": ["This type tries to convince others to do the right thing from a moral standpoint.", "View justice as an extremely important value to restore humans to a certain standard.", "This type is more compliant to their ideals."],
                "9": ["When facing conflict, the principle is foremost and will drive home their point, even if it causes arguments.", "More driven, having difficulty taking a break.", "When handling stress, at first try harder, but then may end up being moody."],
                };

var mistype2 = {"1": ["Highly personal.", "Seek close connection.", "Unrestrained in positive feelings, but more difficult to express negative feelings."],
                "3": ["This type attempts to get others to like them by doing good things for them, focusing on the other person.", "Openly sentimental and emote easily.", "Overexert themselves and lose patience, blowing up.", "Feel uncomfortable going after goals directly, feeling it would be too selfish."],
                "4": ["This type tends to move toward others and engage them.", "Looks for people to rescue.", "Aware of others’ feelings, but unaware of own needs."],
                "5": ["This type is emotionally expressive and highly people-oriented.", "Copes by winning people over.", "Go by feelings."],
                "6": ["This type wants to be loved and be important to others.", "Try to win favor by operating out of warmth and friendliness, offering their love and friendship.", "“Throw out net of feelings” to see whom they can sweep into their lives.", "Want to be close with others.", "Openly warm and demonstrative about how they feel toward others."],
                "7": ["Deeply feeling, with emotions changing less.", "More interpersonal, genuinely friendly, warm, and interested in others.", "Desire to be important.", "Want others to need them.", "Possessive of their friends due to high investment.", "Like to indulge in sharing feelings and intimacies."],
                "8": ["Do so indirectly, often disguised as concern for others.", "Difficulty communicating anger, even though they may be very upset with someone, resorting to indirect approaches.", "This type tends to handle conflict with covert neediness and manipulation.", "This type, when stressed, looks like an unhealthy Type B—aggressive and dominating."],
                "9": ["The way this type loves is by understanding what needs to be met, and trying to meet them in order to get closer and to be relied on.", "Sharp sense of own identity.", "When stressed, become more self-important and aggressive.", "Goes the extra mile for you."],
                };

var mistype3 = {"1": ["Pragmatic, driven by goals. Efficient for the sake of just getting it done.", "More adaptable to get desired result.", "More able to mask what is bothering them.", "Detachment of feelings.", "“Be like me—I have got it together. Offers themselves as exemplars of individual perfection."],
                "2": ["This type attempts to get others to like them by developing excellence, thus gaining attention.", "More composed and have difficulty accessing feelings.", "Overexert themselves and burn out, becoming detached and passive.", "Are very goal-driven."],
                "4": ["Tend to focus on task, on efficiency, on performance, pushing aside feelings.", "Might be seen from the other type as inauthentic."],
                "5": ["Very goal-oriented.", "Changes interests and careers rapidly to seek success.", "Tend to promote themselves.", "Highly sociable."],
                "6": ["See themselves as soloists, wanting to excel to be the best they can be.", "Tend to be smooth and composed."],
                "7": ["This type desires to reinforce their feeling of superiority and hence sense of self.", "This type does so in order to create exclusivity for being of the “in crowd.”", "Desires to rise above other competitively.", "This type has an inflated sense of self-worth.", "Cool, in control, projecting the impression that they are perfectly together, with no emotional or personal problems."],
                "8": ["This type spends a lot of time comparing themselves to others.", "Are natural managers and technicians.", "Fear failure because of personal humiliation.", "Focus on others’ opinions in conjunction with achievements."],
                "9": ["This type, when stressed, looks like an unhealthy Type B—disengaged and apathetic.", "Highly motivated self-starters.", "Try to garner attention from people who believe are important to them.", "Get excited about projects."],
                };

var mistype4 = {"1": ["Want to sort out feelings first, deal with duties after. Might not be able to mobilize self to meet responsibilities.", "Critical over others’ lack of awareness of sensitivities.", "Respond by withdrawing.", "This type, when growing, looks like a healthy Type A—more objective and principled."],
                "2": ["This type tends to withdraw from others, hoping that others will seek them out.", "Looks for someone to rescue them.", "Highly aware of own emotional state, but may not recognize impact on others."],
                "3": ["Want to accomplish things too, but when difficult feelings arise, they want to stop and process before returning to tasks.", "Might be seen from the other type as unprofessional."],
                "5": ["This type is more self-absorbed and emotionally volatile, expressing emotions and expecting responses in certain ways.", "Tend to focus on disappointments in love and with childhood."],
                "6": ["This type becomes depressed because of disappointment in self for losing / messing up opportunities.", "Relate primarily to own inner emotional state.", "True introverts."],
                "7": ["Excessive and indulgent with emotional extremes.", "Cherishing things for the sake of beauty."],
                "8": ["This type finds it difficult to let go of wounds and “getting over it.”", "This type shows vulnerability, but in reality are rather strong inside."],
                "9": ["The artistry of this type is more personal and self-revealing.", "Often deals with the tragic.", "Withdraw from others to protect themselves and give time to process emotions.", "Detached from whatever caused them pain.", "Not comforted by seeing others living a happier, more normal life."],
                };

var mistype5 = {"1": ["More from the mind. Relative lack of certainty and difficulty with discernment.", "More interested in how ideas relate to other thoughts that arise in the mind.", "Constantly investigating and questioning assumptions."],
                "2": ["This type is emotionally detached and can be known as loners.", "Copes by detaching from hurt and isolating self.", "Go by intellectual concepts."],
                "3": ["Very process-oriented, not caring much about the final goal.", "Follow their ideas wherever it takes them.", "Tend to be secretive.", "Usually loners."],
                "4": ["This type might have intense feelings but share them with few people, fueling thoughts and imagination.", "Tend to focus on inner emptiness and feelings of meaningless."],
                "6": ["Tend to be more non-linear. They are interested in finding out where theories break down and develop original ideas.", "Feel can mostly only trust their minds to come to conclusions."],
                "7": ["This type tends to be more socially isolated and withdrawn.", "Their gift is intense focus and concentration.", "Focus more on the nihilistic, realistic side of things.", "This type, when stressed, looks like an unhealthy Type B—hyperactive and scattered."],
                "8": ["This type tends to stay in their heads more, having more difficulty being grounded and practical.", "This type, when growing, looks like  healthy Type B—self-confident and decisive."],
                "9": ["This type is more strong-minded and resistant to the influence of others.", "More suspicious of people.", "More involved with details.", "Tend to speculate on problems.", "Attempts to see if their ideas might come true.", "Often get lost in complex interpretations of reality.", "Are afraid of being overwhelmed by the world and use thinking as a defense against it."],
                };

var mistype6 = {"1": ["Anxious, indecisive, ambivalent, reactive.", "Compliant to demands of other people.", "“Inner Committee” in the head.", "Guilty when doing something contrary to the commitments to allies, beliefs, and authorities."],
                "2": ["This type wants to have the approval and support of others.", "Try to win favor by being playful and silly to elicit emotional response.", "Warily invite selected people into their lives.", "Want to create partnerships with others that will support them—but not too close.", "Ambivalent about feelings, often anxious."],
                "3": ["Tend to feel awkward about taking the spotlight.", "Tend to be (often endearingly) more nervous and awkward."],
                "4": ["This type becomes depressed when fearing they have done something to make an authority figure mad at them.", "Usually relate well to people.", "More ambiverted."],
                "5": ["Tend to be more linear and analytical because more interested in troubleshooting and predictions.", "Do not really trust their own minds to come to meaningful conclusions."],
                "7": ["This type tends to react to anxiety by fretting and becoming more anxious.", "Persistent sense of commitment, having a higher sense of responsibility and working to meet all obligations first."],
                "8": ["This type becomes aggressive because they do not want to be pushed around anymore (more defensive).", "Eventually may yield if enough pressure applied to them."],
                "9": ["Have a more difficult time disguising feelings.", "Tend to be suspicious of unknown people and situations.", "This type, when growing, looks like  healthy Type B—relaxed and optimistic."],
                };

var mistype7 = {"1": ["This type, when stressed, looks like an unhealthy Type A—perfectionistic and critical.", "Usually very optimistic about the future.", "“Feel” their mission.", "“Perfectionism” drives them to become frustrated because of failed expectations (the optimistic outcome did not occur).", "Spontaneous in plans, sometimes scattered. Unselfconscious socially. Driven by anxiety."],
                "2": ["Quicker, more fickle emotions.", "Do not get as involved in people’s lives, but like to float around people to bring more enjoyment.", "Desire to have a good time with people around.", "Do not want to be needed by others—have little patience for anyone who is too dependent on them.", "Tend to be less attached to people, not as clingy.", "Like to indulge in filling minds with interesting possibilities and concepts."],
                "3": ["This type desires to possess things and hence sense of self.", "This type does so to experience whatever is new and exciting right away.", "Desires continuous stream of environmental stimulation.", "This type has an inflated appetite.", "Have many more rough edges, rarely seeming as perfect or as coolly self-contained as Type A."],
                "4": ["Excessive and indulgent with possessions and experiences.", "Cherishing things for the sake of stimulation."],
                "5": ["This type is highly gregarious.", "Their gift is breadth of vision and synthesis.", "Focus more on the positive side of things.", "This type, when growing, looks like a healthy Type A—focused and fascinated by life."],
                "6": ["This type tends to react to anxiety by looking for enjoyable distractions.", "Much more spontaneous, resistant to having too many expectations placed on them."],
                "8": ["This type is primarily interested in variety.", "See themselves as idealistic optimists, often getting ahead of themselves."],
                "9": ["This type loves excitement.", "As they become unhealthier, become more demanding and excessive.", "Seeks for euphoria and elation."],
                };

var mistype8 = {"1": ["This type tries to convince using personal convictions and own self-confidence.", "View justice with more of a visceral response, rushing in to protect others.", "This type is more given over to their gut response."],
                "2": ["Do so directly, making it clear that there is a power struggle.", "Openly aggressive, very direct in communication.", "This type tends to handle conflict with intense passion in interpersonal conflicts.", "This type, when growing, looks like a healthy Type A—open-hearted and caring."],
                "3": ["This type is self-assertive and want others to give way as not to waste energy.", "Are leaders who want to make the world conform to their personal vision.", "See failure as an opportunity to learn and come back stronger.", "Focus on achieving purposes rather than others’ opinions."],
                "4": ["This type tries to toughen up and “get over it” in order to maintain independence and personal authority.", "This type shows strength, but in reality are rather vulnerable inside."],
                "5": ["This type is more instinctual and are of practical action.", "This type, when stressed, looks like an unhealthy Type B—secretive and fearful."],
                "6": ["This type becomes aggressive to achieve what they want (more offensive).", "More pressure encourages them to remain defiant."],
                "7": ["This type is primarily interested in intensity.", "See themselves as hard-nosed realists, generally remaining grounded and down to earth."],
                "9": ["Much more openly assertive and do not mind engaging in conflicts to make a point.", "As they become unhealthier, become angrier and more aggressive."],
                };

var mistype9 = {"1": ["When facing conflict, even if this type may hold strong personal convictions, they generally do not want to start arguments.", "Enjoy down time, easily able to take a break.", "When handling stress, become disengaged and resistant, but then may end up being anxious and reactive."],
                "2": ["The way this type loves is by supporting others emotionally without looking for much in return.", "Self-effacing and accommodating.", "When stressed, become more self-effacing and withdrawn.", "Wishes you well and offers reassurance."],
                "3": ["This type, when growing, looks like a healthy Type A—self-developing and energetic.", "Often kept motivated and on track through accountability.", "Trouble doing good things for themselves.", "Get excited about free time and comforts."],
                "4": ["The artistry of this type often expresses idealization.", "Often deals in the commonplace.", "Withdraw from others to remove attention from circumstances that threaten them.", "Detached both from external world and emotions.", "Comforted by seeing the world through rose-colored glasses."],
                "5": ["This type is more patient and accommodating.", "Much more trusting of people.", "More involved with generalities.", "Tend to focus on identifying solutions to problems.", "Tend to ruminate on their fantasies.", "Often simplify and reinterpret reality.", "Feel at ease in the world and use thinking as a reflection of a desire to merge with the world."],
                "6": ["Like to remain easygoing.", "Tend to be much more trusting of others.", "This type, when stressed, looks like an unhealthy Type A—anxious and worried."],
                "7": ["This type tends to avoid conflict or over excitement.", "As they become unhealthier, become more passive and indifferent.", "Seeks to maintain state of contentment--not too excited nor in discomfort."],
                "8": ["Dislike contention and would rather agree to keep the peace.", "As they become unhealthier, become more passive and disengaged."],
                };

var mistypes = {"12": ["These two types are often easy to tell apart, unless someone is differentiating between wing types. Both serious, conscience-driven, of service, can be very altruistic.", "", ""],
                "13": ["Both efficient and highly organized, but..", "", "Both put feelings aside for the sake of efficiency, becoming cool and impersonal but…", "", ""],
                "14": ["These two types are often easy to tell apart. They might seem similar if focusing mostly on the negative aspects: perfectionistic, dissatisfied, frustrated, perceived as fussy or picky.", "Both critical and picky, but…", "", "Both are related because…"],
                "15": ["Can both be considered deep thinking types, but…", "", ""],
                "16": ["These two types are often easy to tell apart.", "Both are compliant types (“should” or “must”), but…", "", "Both may feel guilty, but…"],
                "17": ["Both are related because…", "Both share idealism and a sense of “mission,” holding high ideals, but…", "", "Both might express “perfectionism”, but…", "Still, there exist a number of differences."],
                "18": ["Both have strong wills and action-oriented, but…", "Both are involved with justice, but…", "Both may have aggressive impulses, but…"],
                "19": ["These two types may be confusing if someone is differentiating between wing types. This could be difficult. Both can be idealistic, philosophical, and somewhat withdrawn, but…", "", ""],
                "23": ["These two types may be confusing if someone is differentiating between wing types. Both lean into the desire to be liked and please others, but…", "", "", "Both may seem ambitious, but…"],
                "24": ["Both are feeling, sensitive types. Both (and really, all types) can be depressed. They put great emphasis on the ups and downs of relationships, but…", "", ""],
                "25": ["These two types are very easy to tell apart. Both may feel rejected easily, but…", "", ""],
                "26": ["Both are warm and engaging, wanting to be liked, but…", "Both ingratiate themselves with people, but…", "Both types are emotional, but…", "", ""],
                "27": ["Both can be emotional and histrionic, but…", "Both are gregarious and enjoy being with people, but…", "", "", "", ""],
                "28": ["Both may dominate others, but…", "", "Both struggle with rejection, but…", "Both are related because…"],
                "29": ["Both are interpersonal, both tend to put others’ needs before their own, both believe in service, but...", "", "", ""],
                "34": ["These two types may be confusing if someone is differentiating between wing types. But…", ""],
                "35": ["Both may be intelligent thinkers, but...", "", "", ""],
                "36": ["Both can be focused on work and performance, but...", ""],
                "37": ["Both are aggressive or assertive types, both are interested in enjoying different aspects of success, but...", "Both can be trendsetters, but...", "", "Both may seem narcissistic and grandiose, but...", ""],
                "38": ["Both are ambitious and competitive, but...", "", "", ""],
                "39": ["Both are related because…", "Both are highly adaptable and interested in gaining acceptance from others, but...", "", ""],
                "45": ["These two types may be confusing if someone is differentiating between wing types. Both are withdrawn types, but…", ""],
                "46": ["Both may identify with negative emotions, but...", "", ""],
                "47": ["These two types are very easy to tell apart. Both may tend to be excessive, but...", ""],
                "48": ["These two types are fairly easy to tell apart. Both may encounter passionate and intense feelings, but...", ""],
                "49": ["Both may be creative, but...", "", "Both maybe withdrawn, but...", "", ""],
                "56": ["Both are thinking types, but...", ""],
                "57": ["These two types are easy to tell apart. Both are very curious and exploratory, but...", "", "", "Both are related because…"],
                "58": ["Both see themselves as outsiders and easily feel rejected, both are highly independent, both believe in direct communication, but...", "Both are related because…"],
                "59": ["Both may be intelligent, but...", "", "", "", "Both may ask “What if?” questions, but...", "", ""],
                "67": ["These two types may be confusing if someone is differentiating between wing types. Both are thinking types, driven by anxiety, but…", ""],
                "68": ["Both may be aggressive, but...", ""],
                "69": ["Both concerned with security and maintaining the status quo, both tend to take modest views of themselves, but...", "", "Both are related because…"],
                "78": ["Both types are aggressive, but...", ""],
                "79": ["These two types are relatively easy to tell apart. Both can be rather busy and happy, but...", "", ""],
                "89": ["These two types may be confusing if someone is differentiating between wing types.", ""],
                }

var list_mistypes = [mistype1, mistype2, mistype3, mistype4, mistype5, mistype6, mistype7, mistype8, mistype9];

var grouptype1 = {"Center": "Body1",
                    "Social": "Compliant1",
                    "Conflict": "Competent1",
                    "Relational": "Frustration1"
                };

var grouptype2 = {"Center": "Heart2",
                    "Social": "Compliant2",
                    "Conflict": "Positive Outlook2",
                    "Relational": "Rejection2"
                };

var grouptype3 = {"Center": "Heart3",
                    "Social": "Assertive3",
                    "Conflict": "Competent3",
                    "Relational": "Attachment3"
                };

var grouptype4 = {"Center": "Heart4",
                    "Social": "Withdrawn4",
                    "Conflict": "Reactive4",
                    "Relational": "Frustration4"
                };

var grouptype5 = {"Center": "Mind5",
                    "Social": "Withdrawn5",
                    "Conflict": "Competent5",
                    "Relational": "Rejection5"
                };

var grouptype6 = {"Center": "Mind6",
                    "Social": "Compliant6",
                    "Conflict": "Reactive6",
                    "Relational": "Attachment6"
                };

var grouptype7 = {"Center": "Mind7",
                    "Social": "Assertive7",
                    "Conflict": "Positive Outlook7",
                    "Relational": "Frustration7"
                };

var grouptype8 = {"Center": "Body8",
                    "Social": "Assertive8",
                    "Conflict": "Reactive8",
                    "Relational": "Rejection8"
                };

var grouptype9 = {"Center": "Body9",
                    "Social": "Withdrawn9",
                    "Conflict": "Positive Outlook9",
                    "Relational": "Attachment9"
                };

var groupexp = {"Center": "<b>Centers</b>: Each Centre of the Enneagram (Body, Heart, Mind) describes the main imbalances that exist in each personality type.",
                    "Social": "<b>Social styles</b>: There are three ways (Assertive, Withdrawn, Compliant) in which people tried to solve their inner conflicts. These three ways also describe how people try to meet their needs.",
                    "Conflict": "<b>Conflict styles</b>: These approaches describe how each type handles conflict, adversity, and situations in which our needs are not met.",
                    "Relational": "<b>Relational styles</b>: Object Relations is a theory that comes from psychoanalysis that states (in a very small nutshell) that our first relationships as babies form the expectations of our adult relationships."
                }

var grouptypes = [grouptype1, grouptype2, grouptype3, grouptype4, grouptype5, grouptype6, grouptype7, grouptype8, grouptype9];

var groupdescriptions = {"Body8": "To compensate with loss of Body, the personality tries to create and maintain a sense of self. This type acts out their anger and instinctual energies. In other words, when this type feels anger building in them, they immediately respond to it in some physical way, raising their voices, moving more forcefully. Others can clearly see that these types are angry because they give themselves permission to express their anger physically.",
                        "Body9": "To compensate with loss of Body, the personality tries to create and maintain a sense of self. This type denies their anger and instinctual energies as if to say, 'What anger? I am not a person who gets angry.' This type is the type most out of touch with their anger and instinctual energies, often feeling threatened by them. Of course, this type gets angry like everyone else, but tries to stay out of their darker feelings by focusing on idealizations of their relationships and their world.",
                        "Body1": "To compensate with loss of Body, the personality tries to create and maintain a sense of self. This type attempts to control or repress their anger and instinctual energy. They feel that they must stay in control of themselves, especially of their instinctual impulses and angry feelings at all times. They would like to direct these energies according to the dictates of their highly developed inner critic (superego), the source of their strictures on themselves and others.",
                            "Heart2": "To compensate with loss of Heart, the personality tries to create and maintain a personal identity that will overcome negative feelings. This type attempts to control their shame by getting other people to like them and to think of them as good people. They also want to convince themselves that they are good, loving people by focusing on their positive feelings for others while repressing their negative feelings (such as anger and resentment at not being appreciated enough). As long as this type can get positive emotional responses from others, they feel wanted and are able to control feelings of shame.",
                            "Heart3": "To compensate with loss of Heart, the personality tries to create and maintain a personal identity that will overcome negative feelings. This type tries to deny their shame, and are potentially the most out of touch with underlying feelings of inadequacy. This type learns to cope with shame by trying to become what they believe a valuable, successful person is like. Thus, this type learns to perform well, to be acceptable, even outstanding, and are often driven relentlessly in their pursuit of success as a way of staving off feelings of shame and fears of failure.",
                            "Heart4": "To compensate with loss of Heart, the personality tries to create and maintain a personal identity that will overcome negative feelings. This type attempts to control their shame by focusing on how unique and special their particular talents, feelings, and personal characteristics are. This type highlights their individuality and creativity as a way of dealing with their shameful feelings, although this type is the type most likely to succumb to feelings of inadequacy. This type also manages their shame by cultivating a rich, romantic fantasy life in which they do not have to deal with whatever in their life seems drab or uninteresting to them.",
                            "Mind5": "To compensate with loss of Mind, these types become very motivated to find sources of security and confidence. This type has fears about the outer world and about their capacity to cope with it. Thus, they cope with their fear by withdrawing from the world. This type becomes secretive, isolated loners who use their minds to penetrate into the nature of the world. This type hopes that eventually, as they understand reality on their own terms, they will be able to rejoin the world and participate in it, but they never feel they know enough to participate with total confidence. Instead, they involve themselves with increasingly complex inner worlds.",
                            "Mind6": "To compensate with loss of Mind, these types become very motivated to find sources of security and confidence. This type exhibits the most fear of all three types, largely experienced as anxiety, which causes them to be the most out of touch with their own sense of inner knowing and confidence. This type has trouble trusting their own minds, so they are constantly looking outside themselves for something to make them feel sure of themselves. They might turn to philosophies, beliefs, relationships, jobs, savings, authorities, or any combination of the above. But no matter how many security structures they create, This type still feels doubtful and anxious. They may even begin to doubt the very people and beliefs that they have turned to for reassurance. This type may also respond to their fear and anxiety by impulsively confronting it— defying their fear in the effort to be free of it.",
                            "Mind7": "To compensate with loss of Mind, these types become very motivated to find sources of security and confidence. This type has fear about their inner world. There are feelings of pain, loss, deprivation, and general anxiety that this type would like to stay clear of as much as possible. To cope with these feelings, this type keeps their minds occupied with exciting possibilities and options— as long as they have something stimulating to anticipate, this type feels that they can distract themselves from their fears. This type, in most cases, does not stop merely at thinking about these options, however. As much as possible they attempt to actually do as many of their options as they can. Thus, this type can be found staying on the go, pursuing one experience after another, and keeping themselves entertained and engaged with their many ideas and activities.",
                            "Compliant1": "People whose dominant Social Style is 'Compliant' respond to problems, threats, and obstacles by conforming to an internalized set of rules, ideals, or codes of conduct. This type wants autonomy, so they try to earn it according to the rules. If they do their work better than anyone else, no one will interfere with them). Under stress, this type escalates their principles into perfectionism or workaholism. If they are perfect, no one has the can criticize them. This type believes they are morally superior to others.",
                            "Compliant2": "People whose dominant Social Style is 'Compliant' respond to problems, threats, and obstacles by conforming to an internalized set of rules, ideals, or codes of conduct. This type wants attention, and try to get it by following the rules. If this type loves, helps, and cares enough for others, they will earn attention from others. If this type does not receive enough attention, they will increase the amount of help they give. If they are all-loving saints, no one will reject them, and they will be loved (the ultimate attention) in return. This type sets themselves up as superior by making others dependent on them.",
                            "Compliant6": "People whose dominant Social Style is 'Compliant' respond to problems, threats, and obstacles by conforming to an internalized set of rules, ideals, or codes of conduct. This type wants security, and tries to get it by following the rules. If this type is sufficiently dedicated and committed to an authority figure, they will earn security from it. If this type does not receive enough security, they will either strengthen their commitment to their current authority figure (to give it a chance to provide more security), or they will rebel against it and seek security from another source. Their commitment to their cause/belief/authority figure gives them confidence and makes them look down upon those with different beliefs.",
                            "Withdrawn4": "People whose dominant Social Style is 'Withdrawn' perceive a distinct sense of the self being small, weak, or vulnerable, and easily overwhelmed by the world. This type wants attention and seek it by withdrawing from the superficial world of the ordinary. This type also withdraws by being different, unique, and mysterious. If this type is sufficiently unique, distant, and mysterious, they will attract the attention from those who care. Playing hard to get is a test to make sure others care enough about the them. This type spends a large part of their time daydreaming and fantasizing about the attention they would like. This type enjoys these fantasies so much that they have a hard time waking up from their daydreams. Under stress, this type will retreat further into their imagination to sustain their self-image.",
                            "Withdrawn5": "People whose dominant Social Style is 'Withdrawn' perceive a distinct sense of the self being small, weak, or vulnerable, and easily overwhelmed by the world. This type wants security and seek it by withdrawing from a world they see as threatening. This type also withdraws by minimizing their needs and dependencies. This type spends large amounts of time studying and thinking about the world -- so much so that they become more attached to their interpretation of the world than to direct observation. Under stress, this type retreats further into their minds to understand the source of the stress.",
                            "Withdrawn9": "People whose dominant Social Style is 'Withdrawn' perceive a distinct sense of the self being small, weak, or vulnerable, and easily overwhelmed by the world. This type wants autonomy and seek it by withdrawing from an endlessly changing world to get their own peaceful and stable space. This type also withdraws by minimizing their wants and desires. This type enjoys their time relaxing and fantasizing about their harmonious world (inner and outer). However, this type falls into the trap of becoming more attached to their idealized relationships than to their real relationships. Under stress or pressure to change, This type hangs on to their idealizations rather than giving up the stability of the status quo.",
                            "Assertive3": "People whose dominant Social Style is 'Assertive' see the world as offering up what they need; their personal philosophy tends to be that the best things come to those who actively go after them. This type wants attention and they demand that others give it. This type feels important and expects others to praise them. When that doesn't work, this type will determine the values of their 'audience' and adapt themselves to be more favourable to others.",
                            "Assertive7": "People whose dominant Social Style is 'Assertive' see the world as offering up what they need; their personal philosophy tends to be that the best things come to those who actively go after them. This type wants security and fulfillment and they demand that others and the world provide it. This type feels that they deserve to have fun and entertainment and if they don't get it here, they will seek it elsewhere. When others don't provide satisfaction, this type will seek it elsewhere or will try to indulge themselves.",
                            "Assertive8": "People whose dominant Social Style is 'Assertive' see the world as offering up what they need; their personal philosophy tends to be that the best things come to those who actively go after them. This type wants autonomy and demand that they get it. This type will push others out of the way so he can do things his way. This type wants to be in charge and in control of their environment. If they lose that control, they will push back, become confrontational, or contest those who are in charge.",
                            "Positive Outlook2": "People whose dominant Harmonic approach is a 'Positive Outlook' are generally optimistic and tend to avoid negative thoughts or situations. This type can get into conflicts by being too clingy, worried, and self-important. This type tends to focus on their own positive qualities, while repressing their own negative thoughts or feelings. This type believes that they are good and that their good intentions will win them positive approval from others. What others think of this type is very important to this type. As a result, this type is always looking for ways to meet the needs of others and finding ways to please others. This type often rejects their own needs in favour of fulfilling the needs of others.",
                            "Positive Outlook7": "People whose dominant Harmonic approach is a 'Positive Outlook' are generally optimistic and tend to avoid negative thoughts or situations. This type can get into conflicts by being impatient, irresponsible, and excessive. This type tends to focus on their positive expectations for satisfaction and fulfillment. This type is in fact fleeing from a threatening internal world and seeking security in the external world. If this type slows down, their minds may be drawn into the inner world of grief, sadness, and disappointment. Their quick minds avoid dealing with conflict and problems through distraction and constant activity. This type does not typically internalize their experiences; they remain somewhat unattached to people and things. In conflict, this type can quickly discard things and cancel commitments (i.e., the needs of others) without feelings of regret. It is easier to move on to happier things than to stay with things that depress. This type tends to reject the needs of others in favour of fulfilling their own.",
                            "Positive Outlook9": "People whose dominant Harmonic approach is a 'Positive Outlook' are generally optimistic and tend to avoid negative thoughts or situations. This type can get into conflicts by being too complacent, inattentive, and stubborn. This type tends to focus on their positive and harmonious relationships with their environment. This type has a difficult time dealing with conflict or change because it disrupts their peace and stability. This type, therefore, tries to deny or avoid these problems by strengthening their attachment to the status quo. These problems will take care of themselves, so why bother dealing with them. This type focuses on the needs of others, often accommodating to others. This type tries to balance the needs of others with their own needs of autonomy.",
                            "Competent1": "People whose dominant Harmonic approach is 'Competency' try solving problems in an objective, unemotional manner. This type can get into conflicts by being too impatient, rigid, and critical. This type focuses on solving problems by doing what's right. This type strongly believes that by following the rules, their faith, or their principles they will come to a just and fair solution. This type feels that they must put their own wants (and feelings) aside in order to remain objective (and autonomous from influence). This type may appear cold to others and that they don't take into account the feelings of others.",
                            "Competent3": "People whose dominant Harmonic approach is 'Competency' try solving problems in an objective, unemotional manner. This type can get into conflicts by being too competitive, insincere, and boastful. Threes focus on being efficient and meeting their goals. When confronted with problems, they can easily set aside their own feelings and focus on the task at hand. In general, Threes want to follow existing structures. However, Threes are pragmatists that will cut corners to realize their goals.",
                            "Competent5": "People whose dominant Harmonic approach is 'Competency' try solving problems in an objective, unemotional manner. This type can get into conflicts by being too detached, isolated, and provocative. This type naturally detaches themselves emotionally from the world to be objective. They believe that they have the mental resources to deal with problems. In conflict, this type will want to withdraw and will think for a while before coming back with a solution, often to the irritation of others. This type feels that they can solve things by themselves, without relying on others. They may come back with highly original ideas (thinking outside the box). On the other hand, they may waste their time reinventing the wheel.",
                            "Reactive4": "People whose dominant Harmonic approach is 'Reactive' are emotionally reactive under stress. This type can get into conflicts by being overly moody, temperamental and self-absorbed. This type tends to have (over-) dramatic reactions to problems. They need to process and internalize their experiences. Identity and emotional reactions are highly intertwined in a Four. This type tends to withdraw into their imagination, where problems often escalate into feelings of despair and hopelessness. This type wants to be emotionally open with and trust others, but more so with very close people. Their emotional guard is down so they can let others in.",
                            "Reactive6": "People whose dominant Harmonic approach is 'Reactive' are emotionally reactive under stress. This type can get into conflict by being too pessimistic, suspicious, and doubtful. This type tends to be very anxious people. They are always on the watch for dangers and threats. When conflicts or threats occur, their anxiety comes out, often as long rants, hysterical overreactions, and feelings of inferiority. This type wants to trust others (and others often put their faith in this type), but remain wary of problems. Sometimes they let their guard down (when within the confines of the authority/belief). Other times, they keep their guard up to ensure that others do not take advantage of them.",
                            "Reactive8": "People whose dominant Harmonic approach is 'Reactive' are emotionally reactive under stress. This type can get into conflict by being too willful, defiant and confrontational. This type tends to not censor their own impulses or emotional reactions. This type wants to feel the realness of conflict to give themselves a stronger sense of being. When conflicts occur, this type is very quick to challenge and confront them. This type keep their guard up all the time and want to minimize their dependence on (and trust in) others. They do not want others to see their vulnerable side.",
                            "Attachment3": "People with the attachment object relation tend to have a sense of contentment that their needs (with people, situations, thoughts) are being met. This type adapts their self-image to be consistent with the expectations and values of others. This type is aware of what is valued by their friends, family, coworkers, etc. and they strive to attain those values. That way, they can receive the attention and validation from others. Their sense of self is based on an attachment to their self-image of a successful, valuable person.",
                            "Attachment6": "People with the attachment object relation tend to have a sense of contentment that their needs (with people, situations, thoughts) are being met. This type adapts their belief systems to be consistent with those of an authority figure or system. This type doubt their own ability to cope with the world, so they seek security through another person or system. Their sense of self is based on an attachment or association and loyalty to important people or groups.",
                            "Attachment9": "People with the attachment object relation tend to have a sense of contentment that their needs (with people, situations, thoughts) are being met. This type adapts (or accommodates) their own wants and opinions to be consistent with those of others. This type want peace, so why rock the boat? By going along with others, they can attain the harmony they seek. This type bases their sense of self on their attachment to their idealized (internalized harmonious) view of the world.",
                            "Frustration1": "People with the frustration object relation know what will make them happy, but they feel they seldom have it. This type is searching for ideal autonomy. That means perfection and complete self-control. This type focuses on what's wrong or out of place in a given situation. They become frustrated when they see that things don't live up to their standards and when they feel obligated to improve everything. Their sense of self is based on this frustration - it shows that they still care about making things better.",
                            "Frustration4": "People with the frustration object relation know what will make them happy, but they feel they seldom have it. This type is searching for ideal attention -- a partner who completely understands and appreciates them. This type focuses on what's missing in others and in themselves. Despite their longing for an ideal partner, their actual partner has flaws and isn't quite what this type is looking for. This type seeks validation and attention from others, but feel they must be different and distant from others to get it. As a result, their strategy for attention doesn't often work, leading to a sense of frustration that maintains their sense of self.",
                            "Frustration7": "People with the frustration object relation know what will make them happy, but they feel they seldom have it. This type is searching for ideal security and contentment. This type focuses on the fun they are not having. The current experience isn't quite as fun as they hoped it would be. Their mind quickly jumps to opportunities and experiences that they could be having rather than the one they are currently experiencing. This type gets frustrated with the present and seek security in the future. Their sense of self is based on the search rather than on the experience.",
                            "Rejection2": "People with the rejection object relation feel that they have been rejected by others. Consequently, their relationships often have issues of not wanting to be nurtured or touched. This type rejects their own needs, their own negative thoughts and emotions. This type offers the only gift she has left: her heart. They focuses on the needs of others and helping, caring, and nurturing them. This type tries to love others so much that others won't reject them. This type bases their sense of self on putting their own needs aside (rejection) and caring for others.",
                            "Rejection5": "People with the rejection object relation feel that they have been rejected by others. This type rejects and minimizes their own needs (especially their physical and emotional ones). This type has only one gift left: their head. This type offers their intelligence and expertise to others, hoping that others will appreciate their knowledge. By building up their own expertise, This type seeks to become important enough not to be rejected further. This type, having cut off their emotional needs, try to not need others, to be independent, and to not need love. This type believes that their lack of emotion will shield them from the pain of further rejection.",
                            "Rejection8": "People with the rejection object relation feel that they have been rejected by others. This type rejects their own needs (especially their emotional, vulnerable side). This type only has one gift left to prevent further rejection: her strength and will. This type believes in their power and know that others can turn to them from strength and leadership. This type expects to be rejected, but because they are so 'tough,' they give the appearance of being able to handle it.",
                        };