var mistype1 = {"2": ["Appeals to principles over personal feelings.", "Defend autonomy.", "Restrained in expression of positive feelings, but easier to express negative feelings."],
                "3": ["Idealists, striving for perfection. Efficient for the sake of reaching the desired standard (how it's done).", "Attached to methods or procedures.", "Less able to conceal irritations and disappointments.", "Able to suppress feelings for the time being.", "\"Listen to me—I know the right way to do things.\" Offers themselves as examples of high moral standard."],
                "4": ["Attend to responsibilities first, feelings later. Would not allow self to “indulge” in feelings very long.", "Critical over others’ inefficiency or failures.", "Respond by pushing other party harder.", "This type, when stressed, looks like an unhealthy Type B—moody and irrational."],
                "5": ["More from an immediate gut response. Emphasis on certainty and judgment.", "More interested in using thoughts to improve themselves and the world.", "Judge from idealistic standards."],
                "6": ["Opinionated and feel like they know themselves.", "Compliant to demands of strict ideals.", "'Inner Critic' in the head.", "Guilty when doing something contrary to personal ideals."],
                "7": ["This type, when growing, looks like a healthy Type A—spontaneous and joyful.", "Hold high standards and expect to be disappointed.", "Know their mission.", "True perfectionism drives them to be angry and critique themselves.", "Rigid in plans, often focused. Quite self-conscious socially. Driven by anger."],
                "8": ["This type tries to convince others to do the right thing from a moral standpoint (even if they have trouble themselves).", "View justice as an extremely important value to restore humans to a certain standard.", "This type is more compliant to their ideals."],
                "9": ["When facing conflict, the principle is a priority for this type and will drive home their point, even if it causes arguments.", "More driven, having difficulty taking a break.", "When handling stress, at first will try harder, but then may end up being moody."],
                };

var mistype2 = {"1": ["Highly personal.", "Seek close connection.", "Unrestrained in positive feelings, but more difficult to express negative feelings."],
                "3": ["This type attempts to get others to like them by doing good things for them, focusing on the other person.", "Openly sentimental and emote easily.", "Overexert themselves and lose patience, blowing up.", "Feel uncomfortable going after goals directly, feeling it would be too selfish."],
                "4": ["This type tends to move toward others and engage them.", "Looks for people to rescue, even if unnecessary.", "Aware of others’ feelings, but unaware of own needs."],
                "5": ["This type is more emotionally expressive and highly people-oriented.", "Copes by winning people over to their side.", "Go by feelings about something."],
                "6": ["This type wants to be loved and be important to others.", "Try to win favor by operating out of warmth and friendliness, offering their love and friendship.", "“Throw out net of feelings” to see whom they can sweep into their lives.", "Want to be close with others and share deeply with them.", "Openly warm and demonstrative about how they feel toward others."],
                "7": ["Deeply feeling, with emotions changing less often.", "More interpersonal, genuinely friendly, warm, and interested in others.", "Stronger desire to be relationally important.", "Want others to need them.", "Possessive of their friends due to high investment.", "Like to indulge in sharing feelings and intimacies."],
                "8": ["Do so indirectly, often disguised as concern for others.", "Difficulty communicating anger, even though they may be very upset with someone, resorting to indirect or lighter approaches.", "This type tends to handle conflict with covert neediness and manipulation.", "This type, when stressed, looks like an unhealthy Type B—aggressive and dominating."],
                "9": ["The way this type loves is by understanding what needs to be met, and trying to meet them as best they can in order to get closer and to be relied on.", "Sharp sense of own identity.", "When stressed, become more self-important and aggressive.", "Goes the extra mile for you."],
                };

var mistype3 = {"1": ["Pragmatic, driven by goals. Efficient for the sake of just getting it done.", "More adaptable to get desired result.", "More able to mask what is bothering them.", "Detachment of feelings.", "\"Be like me—I have got it together.\" Offers themselves as exemplars of individual perfection."],
                "2": ["This type attempts to get others to like them by developing excellence, thus gaining attention.", "More composed and have difficulty accessing feelings.", "Overexert themselves and burn out, becoming detached and passive.", "Are very (sometimes too) goal-driven."],
                "4": ["Tend to focus on task, on efficiency, on performance, pushing aside feelings.", "Might be seen from the other type as inauthentic."],
                "5": ["Very goal-oriented, sometimes can cut corners to get theere.", "Changes interests and careers rapidly to seek success.", "Tend to promote themselves.", "Highly sociable."],
                "6": ["See themselves as soloists, wanting to excel to be the best they can be.", "Tend to be smooth and composed."],
                "7": ["This type primarily desires status symbols (items, experiences, expert knowledge) to feel like themselves.", "This type does so in order to create exclusivity and an air of superiority.", "Desires to rise above others competitively.", "This type tends to have an inflated sense of self-worth.", "Appears cool, in control, projecting the impression that they are perfectly together, with no emotional or personal problems."],
                "8": ["This type spends a lot of time comparing themselves to others in order to rise above them.", "Enjoy the personal success, prestige, and accomplishment that comes with leadership the most.", "Are more focused on how they present themselves in order to preserve image.", "Great at adapting to what is externally asked of them."],
                "9": ["This type, when stressed, looks like an unhealthy Type B—disengaged and apathetic.", "Highly motivated self-starters, sometimes getting lost in projects.", "Try to garner attention from people who they believe are important to them.", "Get most excited about projects."],
                };

var mistype4 = {"1": ["Want to sort out feelings first, deal with duties after. Might not be able to easily mobilize self to meet responsibilities.", "Critical over others’ lack of awareness of sensitivities.", "Respond by withdrawing.", "This type, when growing, looks like a healthy Type A—more objective and principled."],
                "2": ["This type tends to withdraw from others, hoping that others will seek them out.", "Looks for someone to rescue them.", "Highly aware of own emotional state, but may not recognize impact on others."],
                "3": ["Want to accomplish things too, but when difficult feelings arise, they want to stop and process before returning to tasks.", "Might be seen from the other type as unprofessional."],
                "5": ["This type is more self-absorbed and emotionally volatile, expressing emotions and expecting responses in certain ways.", "Tend to focus on disappointments in love and with childhood."],
                "6": ["This type mostly becomes depressed because of disappointment in self for losing / messing up opportunities.", "In a conversation or social setting, find themselves analyzing and relating things back to own inner emotional state.", "True \"introverts\", drawing on their own emotions and experiences to interpret the world."],
                "7": ["Excessive and indulgent with emotional extremes.", "Cherishing things for the sake of beauty."],
                "8": ["This type finds it difficult to let go of wounds and “getting over it.”", "This type shows vulnerability, but in reality are rather strong inside."],
                "9": ["The artistry of this type is more personal and self-revealing.", "Often deals with the tragic.", "Withdraw from others to protect themselves and give time to process emotions.", "Detached from whatever caused them pain.", "Not comforted by seeing others living a happier, more normal life (feel more dissatisfied)."],
                };

var mistype5 = {"1": ["More from wrestling wth the mind. Relative lack of certainty and difficulty with discernment.", "More interested in how ideas relate to other thoughts that arise in the mind.", "Constantly investigating and questioning assumptions."],
                "2": ["This type is more emotionally detached and can be known as lone wolfs.", "Copes by detaching from hurt and isolating self.", "Go by intellectual concepts."],
                "3": ["Very process-oriented, can often get lost in it instead of a goal.", "Follow their ideas wherever it takes them.", "Tend to be secretive.", "Usually more of a loner."],
                "4": ["This type might have intense feelings but share them with few people, feeding and spiraling into their thoughts and imagination.", "Tend to focus on inner emptiness and feelings of meaningless."],
                "6": ["Tend to be more non-linear. They are more interested in finding out where theories break down to develop even more original ideas.", "Feel can mostly only trust their minds to come to meaningful conclusions."],
                "7": ["This type tends to be more socially isolated and withdrawn.", "Their primary gift is intense focus and concentration.", "Focus more on the nihilistic, realistic side of things.", "This type, when stressed, looks like an unhealthy Type B—hyperactive and scattered."],
                "8": ["This type tends to stay in their heads more, having more difficulty being grounded and act practically.", "This type, when growing, looks like  healthy Type B—self-confident and decisive."],
                "9": ["This type is more strong-minded and resistant to the influence of others.", "More suspicious of people, sometimes too cynical.", "Sometimes have difficulty communicating due to tendency to complexify (better with other experts).", "Tend to approach problems by idealizing the problem--scoping out every problem to the problem.", "If they have an idea or theory, tend to quench curiosity by testing it out.", "Often get lost in complex interpretations of reality without a need to break it down.", "Are afraid of being overwhelmed by the world and use thinking as a defense against it, to overcome it intellectually."],
                };

var mistype6 = {"1": ["More unsure and rely on reassurance and well-tested methods.", "Compliant to demands of other people.", "“Inner Committee” in the head.", "Guilty when doing something contrary to the commitments to allies, beliefs, and authorities."],
                "2": ["This type wants to have the approval and support of others.", "Try to win favor by being playful and silly to elicit emotional response.", "Warily invite selected people into their lives.", "Want to create solid partnerships with others that will support them—-but normally not that close.", "Ambivalent about feelings, often anxious."],
                "3": ["Tend to feel awkward about taking the spotlight.", "Tend to be (often endearingly) more nervous and awkward."],
                "4": ["This type mostly becomes depressed when fearing they have done something to make someone mad at them or not like them.", "In a conversation or social setting, find themselves primarily and actively relating well to other people in order to form more secure relatonships.", "More \"ambiverted\", finding themselves balancing their internal safe-spaces and external secure relationships."],
                "5": ["Tend to be more linear. They are more interested in the actions of troubleshooting and predictions.", "Do not really trust their own minds to come to meaningful conclusions."],
                "7": ["This type tends to react to anxiety by fretting and becoming more anxious.", "Persistent sense of commitment, having a higher sense of responsibility and working to meet all obligations first."],
                "8": ["This type becomes aggressive because they do not want to be pushed around anymore (more defensive).", "Eventually may yield in submission if enough pressure applied to them."],
                "9": ["Have a more difficult time disguising negative feelings.", "Tend to be more suspicious of unknown people and situations.", "This type, when growing, looks like  healthy Type B—relaxed and optimistic."],
                };

var mistype7 = {"1": ["This type, when stressed, looks like an unhealthy Type A—perfectionistic and critical.", "Usually very optimistic about the future.", "“Feel” their mission.", "“Perfectionism” drives them to become frustrated because of failed expectations (the optimistic outcome did not occur).", "Spontaneous in plans, sometimes scattered. Unselfconscious socially. Driven by anxiety."],
                "2": ["Quicker, more fickle and changing emotions.", "Do not get as involved in people’s lives, but like to float around people to enjoy life wth others.", "Stronger desire to have a fun time with the people around.", "Do not want to be needed by others—have little patience for anyone who appears to be too dependent on them.", "Tend to be less attached to certain people and jump around more socially.", "Like to indulge in filling minds with interesting possibilities and concepts."],
                "3": ["This type primarily desires to possess material things (items, experiences, interesting knowledge) to feel like themselves.", "This type does so to experience whatever is new and exciting right away before moving onto the next trend.", "Desires continuous stream of environmental stimulation to satiate growing appetite.", "This type tends to have an inflated appetite.", "Appears to have more rough edges, rarely seeming as perfect or as coolly self-contained as Type A."],
                "4": ["Excessive and indulgent with possessions and experiences.", "Cherishing things for the sake of stimulation."],
                "5": ["This type is highly gregarious.", "Their primary gift is breadth of vision and synthesis.", "Focus more on the positive side of things.", "This type, when growing, looks like a healthy Type A—focused and fascinated by life."],
                "6": ["This type tends to react to anxiety by looking for enjoyable distractions.", "Much more spontaneous, resistant to having too many expectations placed on them."],
                "8": ["This type is primarily interested in a variety of exciting things to expand their world.", "Are great thinkers, as they have interesting and plentiful ideas and plans, but have trouble executing all of them to the end.", "Have no particular desire for power, and sometimes can see it as something that prevents their freedom."],
                "9": ["This type loves excitement.", "As they become unhealthier, become more demanding and excessive.", "Seeks for euphoria and elation."],
                };

var mistype8 = {"1": ["This type tries to convince using convictions, experiences, and self-confidence.", "View justice with more of a visceral response, rushing in to protect others.", "This type is more given over to their gut reaction."],
                "2": ["Do so directly, making it clear that there is a power dynamic.", "Openly straightforward, very direct in communication.", "This type tends to handle conflict with intense passion in interpersonal conflicts.", "This type, when growing, looks like a healthy Type A—open-hearted and caring."],
                "3": ["This type wants others to give way immediately as not to waste energy and time in order to rise above them.", "Enjoy the freedom, power to change, and \"untoucheableness\" aspects of leadership the most.", "Can be too caught up in purpose to maintain image.", "Difficulty adapting to what is externally asked of them (desire to maintain independence)."],
                "4": ["This type tries to toughen up and “get over it” in order to maintain independence and personal authority.", "This type shows strength, but in reality are rather vulnerable inside."],
                "5": ["This type is more instinctual and are of practical action, giving over more to impulse.", "This type, when stressed, looks like an unhealthy Type B—secretive and fearful."],
                "6": ["This type becomes aggressive to achieve what they want if something is in the way (more offensive).", "More pressure encourages them to remain defiant and increases anger."],
                "7": ["This type is primarily interested in the intensity of enjoyable things to feel satisfied.", "Are hands-on pragmatists, focusing more on what they can reasonably do in a given time and driving through.", "See gaining power as a means to freedom."],
                "9": ["Much more openly assertive and do not mind engaging in conflicts to make a point, maybe jumping ahead of themselves.", "As they become unhealthier, become angrier, more aggressive, and domineering."],
                };

var mistype9 = {"1": ["When facing conflict, even if this type may hold strong personal convictions, they generally do not want to start arguments.", "Enjoy down time, easily able to take a break.", "When handling stress, become disengaged and resistant, but then may end up being anxious and reactive."],
                "2": ["The way this type loves is by supporting others emotionally, often at an arm's length, without looking for much in return.", "Self-effacing and accommodating.", "When stressed, become more self-effacing and withdrawn.", "Wishes you well and offers reassurance."],
                "3": ["This type, when growing, looks like a healthy Type A—self-developing and energetic.", "Can have exciting projects, but often kept motivated and on track through accountability.", "More reluctant to ask for attention, and discount themselves easily.", "Get most excited about free time and comforts."],
                "4": ["The artistry of this type often expresses idealization and wonder.", "Often deals in the commonplace.", "Withdraw from others to remove attention from circumstances that threaten them, avoiding anxiety and stress, often not giving their emotions a chance.", "Detached both from external world and emotions.", "Comforted by seeing the world through rose-colored glasses."],
                "5": ["This type is more patient and can be overly accommodating.", "More trusting of people, sometimes too trusting.", "Often can easily communicate thoughts due to tendency to simplify", "Tend to approach problems by idealizing the solution.", "If they have an idea or theory, tend to simply share it and leave it at that without the itch to test it out themselves.", "Often simplify and reinterpret reality to distill it to something digestable.", "Feel at ease in the world and use thinking as a reflection of a desire to merge and harmonize with the world."],
                "6": ["Like to remain easygoing and at peace.", "Tend to be more trusting of strangers and other unknowns.", "This type, when stressed, looks like an unhealthy Type A—anxious and worried."],
                "7": ["This type tends to avoid conflict or over excitement.", "As they become unhealthier, become more passive and indifferent.", "Seeks to maintain state of contentment--not too excited nor in discomfort."],
                "8": ["Dislike contention and would rather agree to keep the peace, sometimes erring on being too passive.", "As they become unhealthier, become more passive, disengaged, and depressive."],
                };

var mistypes = {"12": ["These two types are often easy to tell apart, unless someone is differentiating between wing types. Both serious, conscience-driven, of service, can be very altruistic.", "", ""],
                "13": ["Both efficient and highly organized, but..", "", "Both put feelings aside for the sake of efficiency, becoming cool and impersonal but…", "", ""],
                "14": ["These two types are often easy to tell apart. They might seem similar if focusing mostly on the negative aspects: perfectionistic, dissatisfied, frustrated, perceived as fussy or picky.", "Both critical and picky, but…", "", "Both are related because…"],
                "15": ["Can both be considered deep thinking types, but…", "", ""],
                "16": ["These two types are often easy to tell apart.", "Both are compliant types (“should” or “must”), but…", "", "Both may feel guilty, but…"],
                "17": ["Both are related because…", "Both share idealism and a sense of “mission,” holding high ideals, but…", "", "Both might express “perfectionism”, but…", "Still, there exist a number of differences."],
                "18": ["Both have strong wills and action-oriented, but…", "Both are involved with justice, but…", "Both may have aggressive impulses, but…"],
                "19": ["These two types may be confusing if someone is differentiating between wing types. This could be difficult. Both can be idealistic, philosophical, and somewhat withdrawn, but…", "", ""],
                "23": ["These two types may be confusing if someone is differentiating between wing types. Both lean into the desire to be liked and please others, but…", "", "", "Both may seem ambitious, but…"],
                "24": ["Both are feeling, sensitive types. Both (and really, all types) can be depressed. They put great emphasis on the ups and downs of relationships, but…", "", ""],
                "25": ["These two types are very easy to tell apart. Both may feel rejected easily, but…", "", ""],
                "26": ["Both are warm and engaging, wanting to be liked, but…", "Both ingratiate themselves with people, but…", "Both types are emotional, but…", "", ""],
                "27": ["Both can be emotional and histrionic, but…", "Both are gregarious and enjoy being with people, but…", "", "", "", ""],
                "28": ["Both may dominate others, but…", "", "Both struggle with rejection, but…", "Both are related because…"],
                "29": ["Both are interpersonal, both tend to put others’ needs before their own, both believe in service, but...", "", "", ""],
                "34": ["These two types may be confusing if someone is differentiating between wing types. But…", ""],
                "35": ["Both may be intelligent thinkers, but...", "", "", ""],
                "36": ["Both can be focused on work and performance, but...", ""],
                "37": ["Both are aggressive or assertive types, both are interested in enjoying different aspects of success, but...", "Both can be trendsetters, but...", "", "Both may seem narcissistic and grandiose, but...", ""],
                "38": ["Both are ambitious and competitive, but...", "", "", ""],
                "39": ["Both are related because…", "Both are highly adaptable and interested in gaining acceptance from others, but...", "", ""],
                "45": ["These two types may be confusing if someone is differentiating between wing types. Both are withdrawn types, but…", ""],
                "46": ["Both may identify with negative emotions, but...", "", ""],
                "47": ["These two types are very easy to tell apart. Both may tend to be excessive, but...", ""],
                "48": ["These two types are fairly easy to tell apart. Both may encounter passionate and intense feelings, but...", ""],
                "49": ["Both may be creative, but...", "", "Both maybe withdrawn, but...", "", ""],
                "56": ["Both are thinking types, but...", ""],
                "57": ["These two types are easy to tell apart. Both are very curious and exploratory, but...", "", "", "Both are related because…"],
                "58": ["Both see themselves as outsiders and easily feel rejected, both are highly independent, both believe in direct communication, but...", "Both are related because…"],
                "59": ["Both may be intelligent, but...", "", "", "", "Both may ask “What if?” questions, but...", "", ""],
                "67": ["These two types may be confusing if someone is differentiating between wing types. Both are thinking types, driven by anxiety, but…", ""],
                "68": ["Both may be aggressive, but...", ""],
                "69": ["Both concerned with security and maintaining the status quo, both tend to take modest views of themselves, but...", "", "Both are related because…"],
                "78": ["Both types are aggressive, but...", "", ""],
                "79": ["These two types are relatively easy to tell apart. Both can be rather busy and happy, but...", "", ""],
                "89": ["These two types may be confusing if someone is differentiating between wing types.", ""],
                }

var list_mistypes = [mistype1, mistype2, mistype3, mistype4, mistype5, mistype6, mistype7, mistype8, mistype9];

var grouptype1 = {"Best Self": ["I feel like I'm my best self when instead of feeling angry or critical, I...", "Feel less self critical and more self-accepting", "Feel more enthusiastic and optimistic", "Act more naturally and spontaneously", "Shift my attitude away from what's bad in the situation towards what's good", "Plan more activities that are simply for enjoyment"],
                "Worst Self": ["I feel like I'm my worst self when instead of feeling methodical and structured, I...", "Feel indignant because I am not meeting my expectations, others or life in general", "Turn my anger inwards and feel depressed", "Lose trust in myself and/or feel hopeless unloved and unlovable", "Long for what I don't have and feel hopeless about ever getting it."]
                };

var grouptype2 = {"Best Self": ["I feel like I'm my best self when instead of feeling prideful and self-deceptive, I...", "Admit and accept my painful feelings, including anger, sadness and loneliness", "Express myself more creatively and artistically; explore my inner world", "Express my own needs more, including saying no", "Find healthier sources of self-worth than just helping", "Learn to be alone and become more contemplative"],
                "Worst Self": ["I feel like I'm my worst self when I am not only feeling needy, but I also...", "Stop being kind and loving; become irritable and attack sharply", "Become hardened, distrustful and isolated", "Blame and make demands", "Become controlling, try to take charge when it is unnecessary"]
                };

var grouptype3 = {"Best Self": ["I feel like I'm my best self when instead of feeling vain and deceitful, I...", "Spend more time with, and become more committed to, family and friends", "Value what’s best for the group", "Express my own needs more, including saying no", "Get more in touch with my feelings", "Become more vulnerable"],
                "Worst Self": ["I feel like I'm my worst self when instead of feeling driven, I...", "Procrastinate and become indecisive", "Become apathetic", "Neglect myself and possibly numb out with even more work or other distractions", "Run in circles working or become less productive", "Passive-agressively punish people who make me look at my shortcomings"]
                };

var grouptype4 = {"Best Self": ["I feel like I'm my best self when instead of feeling envious and emotionally turbuluent, I...", "Become more self-disciplined and grounded in the here and now", "Do more problem solving and become more practical", "Shift to accentuating more of the positive and less of the negative", "Act on my strong ideals and principles", "Become less controlled by my feelings"],
                "Worst Self": ["I feel like I'm my worst self when I am not only feeling aloof, but I also...", "Try to manipulate others into loving me in the mistaken belief that another's love will replace my own emptiness and loneliness", "Deny and repress my own needs", "Become overly dependent", "Act not like myself to get attention or to feel special"]
                };

var grouptype5 = {"Best Self": ["I feel like I'm my best self when instead of feeling avaricious and detached, I...", "Get in touch with my body, its power, and its energy by moving away from pure thought and toward action", "Trust my instincts more; become more outspoken and spontaneous", "Become more assertive, doing whatever it takes to win when I have a justifiable cause to uphold", "Become energized and motivated by my anger instead of always withdrawing", "Defend myself more effectively; set clear limits"],
                "Worst Self": ["I feel like I'm my worst self when I am not only feeling detached, but I also...", "Do things more impulsively", "Become scattered and distracted"]
                };

var grouptype6 = {"Best Self": ["I feel like I'm my best self when instead of feeling fearful and pessimistic, I...", "Empathize more with others", "See things from a broader point of view", "Take life less seriously and free up my energy", "Put more trust in my own inner authority"],
                "Worst Self": ["I feel like I'm my worst self when instead of feeling dutiful and loyal, I...", "Avoid feeling anxious by always being busy; may become workaholic", "Become reluctant to try anything new if there is any possibility of failing", "Take on a role or image in order to feel more secure", "Tell lies about myself in order to cover up or get ahead"]
                };

var grouptype7 = {"Best Self": ["I feel like I'm my best self when instead of feeling gluttonous and scattered, I...", "Become quieter and more introspective and objective", "Explore subjects in depth and place more value on wisdom and self-discipline", "Become more accepting of both polarities of life; good and bad, happy and sad", "Become more serious and is taken more seriously", "Get in touch with my fears"],
                "Worst Self": ["I feel like I'm my worst self when I am not only feeling scattered, but I also...", "Become cynical and hypercritical; nitpick, snarl, and try to change people", "Become judgemental of myself and others; can't laugh at myself", "Think in terms of black and white and \"know\" I have the truth", "Blame others for preventing me from enjoying life", "Become obsessive about an idea or project", "Feel a pervasive, low-level irritability"]
                };

var grouptype8 = {"Best Self": ["I feel like I'm my best self when instead of feeling lustful and controlling, I...", "Open up to others and reveal my vulnerability", "Become more concerned for the welfare of others", "Become more loving and lovable; express my gentl and tender sides"],
                "Worst Self": ["I feel like I'm my worst self when instead of feeling self-confident, I...", "Withdraw and take less action in the world", "Become less in touch with my feelings", "Fear that others will turn on me", "Feel defeated and depressed", "May feel guilty and turn my aggression against myself"]
                };

var grouptype9 = {"Best Self": ["I feel like I'm my best self when instead of feeling slothful and self-neglecting, I...", "Become more energetic, efficient, and productive", "Narrow my focus", "Acquire more self-confidence", "Live less through others and take more control of my life"],
                "Worst Self": ["I feel like I'm my worst self when I am not only feeling complacent, but I also...", "Become overwhelmed by anxiety and worry", "Become more self-doubting, indecisive, and rigid", "Become more passive and inactive"]
                };

// var groupexp = {"Best Self": ["Become more energetic, efficient, and productive", "Narrow their focus", "Acquire more self-confidence", "Live less through others and take more control of their lives"],
//                 "Worst Self": ["Become overwhelmed by anxiety and worry", "Become more self-doubting, indecisive, and rigid", "Become more passive and inactive"]
//                 };

var grouptypes = [grouptype1, grouptype2, grouptype3, grouptype4, grouptype5, grouptype6, grouptype7, grouptype8, grouptype9];

// var groupdescriptions = {"Body8": "To compensate with loss of Body, the personality tries to create and maintain a sense of self. This type acts out their anger and instinctual energies. In other words, when this type feels anger building in them, they immediately respond to it in some physical way, raising their voices, moving more forcefully. Others can clearly see that these types are angry because they give themselves permission to express their anger physically.",
//                         "Body9": "To compensate with loss of Body, the personality tries to create and maintain a sense of self. This type denies their anger and instinctual energies as if to say, 'What anger? I am not a person who gets angry.' This type is the type most out of touch with their anger and instinctual energies, often feeling threatened by them. Of course, this type gets angry like everyone else, but tries to stay out of their darker feelings by focusing on idealizations of their relationships and their world.",
//                         "Body1": "To compensate with loss of Body, the personality tries to create and maintain a sense of self. This type attempts to control or repress their anger and instinctual energy. They feel that they must stay in control of themselves, especially of their instinctual impulses and angry feelings at all times. They would like to direct these energies according to the dictates of their highly developed inner critic (superego), the source of their strictures on themselves and others.",
//                             "Heart2": "To compensate with loss of Heart, the personality tries to create and maintain a personal identity that will overcome negative feelings. This type attempts to control their shame by getting other people to like them and to think of them as good people. They also want to convince themselves that they are good, loving people by focusing on their positive feelings for others while repressing their negative feelings (such as anger and resentment at not being appreciated enough). As long as this type can get positive emotional responses from others, they feel wanted and are able to control feelings of shame.",
//                             "Heart3": "To compensate with loss of Heart, the personality tries to create and maintain a personal identity that will overcome negative feelings. This type tries to deny their shame, and are potentially the most out of touch with underlying feelings of inadequacy. This type learns to cope with shame by trying to become what they believe a valuable, successful person is like. Thus, this type learns to perform well, to be acceptable, even outstanding, and are often driven relentlessly in their pursuit of success as a way of staving off feelings of shame and fears of failure.",
//                             "Heart4": "To compensate with loss of Heart, the personality tries to create and maintain a personal identity that will overcome negative feelings. This type attempts to control their shame by focusing on how unique and special their particular talents, feelings, and personal characteristics are. This type highlights their individuality and creativity as a way of dealing with their shameful feelings, although this type is the type most likely to succumb to feelings of inadequacy. This type also manages their shame by cultivating a rich, romantic fantasy life in which they do not have to deal with whatever in their life seems drab or uninteresting to them.",
//                             "Mind5": "To compensate with loss of Mind, these types become very motivated to find sources of security and confidence. This type has fears about the outer world and about their capacity to cope with it. Thus, they cope with their fear by withdrawing from the world. This type becomes secretive, isolated loners who use their minds to penetrate into the nature of the world. This type hopes that eventually, as they understand reality on their own terms, they will be able to rejoin the world and participate in it, but they never feel they know enough to participate with total confidence. Instead, they involve themselves with increasingly complex inner worlds.",
//                             "Mind6": "To compensate with loss of Mind, these types become very motivated to find sources of security and confidence. This type exhibits the most fear of all three types, largely experienced as anxiety, which causes them to be the most out of touch with their own sense of inner knowing and confidence. This type has trouble trusting their own minds, so they are constantly looking outside themselves for something to make them feel sure of themselves. They might turn to philosophies, beliefs, relationships, jobs, savings, authorities, or any combination of the above. But no matter how many security structures they create, This type still feels doubtful and anxious. They may even begin to doubt the very people and beliefs that they have turned to for reassurance. This type may also respond to their fear and anxiety by impulsively confronting it— defying their fear in the effort to be free of it.",
//                             "Mind7": "To compensate with loss of Mind, these types become very motivated to find sources of security and confidence. This type has fear about their inner world. There are feelings of pain, loss, deprivation, and general anxiety that this type would like to stay clear of as much as possible. To cope with these feelings, this type keeps their minds occupied with exciting possibilities and options— as long as they have something stimulating to anticipate, this type feels that they can distract themselves from their fears. This type, in most cases, does not stop merely at thinking about these options, however. As much as possible they attempt to actually do as many of their options as they can. Thus, this type can be found staying on the go, pursuing one experience after another, and keeping themselves entertained and engaged with their many ideas and activities.",
//                             "Compliant1": "People whose dominant Social Style is 'Compliant' respond to problems, threats, and obstacles by conforming to an internalized set of rules, ideals, or codes of conduct. This type wants autonomy, so they try to earn it according to the rules. If they do their work better than anyone else, no one will interfere with them). Under stress, this type escalates their principles into perfectionism or workaholism. If they are perfect, no one has the can criticize them. This type believes they are morally superior to others.",
//                             "Compliant2": "People whose dominant Social Style is 'Compliant' respond to problems, threats, and obstacles by conforming to an internalized set of rules, ideals, or codes of conduct. This type wants attention, and try to get it by following the rules. If this type loves, helps, and cares enough for others, they will earn attention from others. If this type does not receive enough attention, they will increase the amount of help they give. If they are all-loving saints, no one will reject them, and they will be loved (the ultimate attention) in return. This type sets themselves up as superior by making others dependent on them.",
//                             "Compliant6": "People whose dominant Social Style is 'Compliant' respond to problems, threats, and obstacles by conforming to an internalized set of rules, ideals, or codes of conduct. This type wants security, and tries to get it by following the rules. If this type is sufficiently dedicated and committed to an authority figure, they will earn security from it. If this type does not receive enough security, they will either strengthen their commitment to their current authority figure (to give it a chance to provide more security), or they will rebel against it and seek security from another source. Their commitment to their cause/belief/authority figure gives them confidence and makes them look down upon those with different beliefs.",
//                             "Withdrawn4": "People whose dominant Social Style is 'Withdrawn' perceive a distinct sense of the self being small, weak, or vulnerable, and easily overwhelmed by the world. This type wants attention and seek it by withdrawing from the superficial world of the ordinary. This type also withdraws by being different, unique, and mysterious. If this type is sufficiently unique, distant, and mysterious, they will attract the attention from those who care. Playing hard to get is a test to make sure others care enough about the them. This type spends a large part of their time daydreaming and fantasizing about the attention they would like. This type enjoys these fantasies so much that they have a hard time waking up from their daydreams. Under stress, this type will retreat further into their imagination to sustain their self-image.",
//                             "Withdrawn5": "People whose dominant Social Style is 'Withdrawn' perceive a distinct sense of the self being small, weak, or vulnerable, and easily overwhelmed by the world. This type wants security and seek it by withdrawing from a world they see as threatening. This type also withdraws by minimizing their needs and dependencies. This type spends large amounts of time studying and thinking about the world -- so much so that they become more attached to their interpretation of the world than to direct observation. Under stress, this type retreats further into their minds to understand the source of the stress.",
//                             "Withdrawn9": "People whose dominant Social Style is 'Withdrawn' perceive a distinct sense of the self being small, weak, or vulnerable, and easily overwhelmed by the world. This type wants autonomy and seek it by withdrawing from an endlessly changing world to get their own peaceful and stable space. This type also withdraws by minimizing their wants and desires. This type enjoys their time relaxing and fantasizing about their harmonious world (inner and outer). However, this type falls into the trap of becoming more attached to their idealized relationships than to their real relationships. Under stress or pressure to change, This type hangs on to their idealizations rather than giving up the stability of the status quo.",
//                             "Assertive3": "People whose dominant Social Style is 'Assertive' see the world as offering up what they need; their personal philosophy tends to be that the best things come to those who actively go after them. This type wants attention and they demand that others give it. This type feels important and expects others to praise them. When that doesn't work, this type will determine the values of their 'audience' and adapt themselves to be more favourable to others.",
//                             "Assertive7": "People whose dominant Social Style is 'Assertive' see the world as offering up what they need; their personal philosophy tends to be that the best things come to those who actively go after them. This type wants security and fulfillment and they demand that others and the world provide it. This type feels that they deserve to have fun and entertainment and if they don't get it here, they will seek it elsewhere. When others don't provide satisfaction, this type will seek it elsewhere or will try to indulge themselves.",
//                             "Assertive8": "People whose dominant Social Style is 'Assertive' see the world as offering up what they need; their personal philosophy tends to be that the best things come to those who actively go after them. This type wants autonomy and demand that they get it. This type will push others out of the way so he can do things his way. This type wants to be in charge and in control of their environment. If they lose that control, they will push back, become confrontational, or contest those who are in charge.",
//                             "Positive Outlook2": "People whose dominant Harmonic approach is a 'Positive Outlook' are generally optimistic and tend to avoid negative thoughts or situations. This type can get into conflicts by being too clingy, worried, and self-important. This type tends to focus on their own positive qualities, while repressing their own negative thoughts or feelings. This type believes that they are good and that their good intentions will win them positive approval from others. What others think of this type is very important to this type. As a result, this type is always looking for ways to meet the needs of others and finding ways to please others. This type often rejects their own needs in favour of fulfilling the needs of others.",
//                             "Positive Outlook7": "People whose dominant Harmonic approach is a 'Positive Outlook' are generally optimistic and tend to avoid negative thoughts or situations. This type can get into conflicts by being impatient, irresponsible, and excessive. This type tends to focus on their positive expectations for satisfaction and fulfillment. This type is in fact fleeing from a threatening internal world and seeking security in the external world. If this type slows down, their minds may be drawn into the inner world of grief, sadness, and disappointment. Their quick minds avoid dealing with conflict and problems through distraction and constant activity. This type does not typically internalize their experiences; they remain somewhat unattached to people and things. In conflict, this type can quickly discard things and cancel commitments (i.e., the needs of others) without feelings of regret. It is easier to move on to happier things than to stay with things that depress. This type tends to reject the needs of others in favour of fulfilling their own.",
//                             "Positive Outlook9": "People whose dominant Harmonic approach is a 'Positive Outlook' are generally optimistic and tend to avoid negative thoughts or situations. This type can get into conflicts by being too complacent, inattentive, and stubborn. This type tends to focus on their positive and harmonious relationships with their environment. This type has a difficult time dealing with conflict or change because it disrupts their peace and stability. This type, therefore, tries to deny or avoid these problems by strengthening their attachment to the status quo. These problems will take care of themselves, so why bother dealing with them. This type focuses on the needs of others, often accommodating to others. This type tries to balance the needs of others with their own needs of autonomy.",
//                             "Competent1": "People whose dominant Harmonic approach is 'Competency' try solving problems in an objective, unemotional manner. This type can get into conflicts by being too impatient, rigid, and critical. This type focuses on solving problems by doing what's right. This type strongly believes that by following the rules, their faith, or their principles they will come to a just and fair solution. This type feels that they must put their own wants (and feelings) aside in order to remain objective (and autonomous from influence). This type may appear cold to others and that they don't take into account the feelings of others.",
//                             "Competent3": "People whose dominant Harmonic approach is 'Competency' try solving problems in an objective, unemotional manner. This type can get into conflicts by being too competitive, insincere, and boastful. Threes focus on being efficient and meeting their goals. When confronted with problems, they can easily set aside their own feelings and focus on the task at hand. In general, Threes want to follow existing structures. However, Threes are pragmatists that will cut corners to realize their goals.",
//                             "Competent5": "People whose dominant Harmonic approach is 'Competency' try solving problems in an objective, unemotional manner. This type can get into conflicts by being too detached, isolated, and provocative. This type naturally detaches themselves emotionally from the world to be objective. They believe that they have the mental resources to deal with problems. In conflict, this type will want to withdraw and will think for a while before coming back with a solution, often to the irritation of others. This type feels that they can solve things by themselves, without relying on others. They may come back with highly original ideas (thinking outside the box). On the other hand, they may waste their time reinventing the wheel.",
//                             "Reactive4": "People whose dominant Harmonic approach is 'Reactive' are emotionally reactive under stress. This type can get into conflicts by being overly moody, temperamental and self-absorbed. This type tends to have (over-) dramatic reactions to problems. They need to process and internalize their experiences. Identity and emotional reactions are highly intertwined in a Four. This type tends to withdraw into their imagination, where problems often escalate into feelings of despair and hopelessness. This type wants to be emotionally open with and trust others, but more so with very close people. Their emotional guard is down so they can let others in.",
//                             "Reactive6": "People whose dominant Harmonic approach is 'Reactive' are emotionally reactive under stress. This type can get into conflict by being too pessimistic, suspicious, and doubtful. This type tends to be very anxious people. They are always on the watch for dangers and threats. When conflicts or threats occur, their anxiety comes out, often as long rants, hysterical overreactions, and feelings of inferiority. This type wants to trust others (and others often put their faith in this type), but remain wary of problems. Sometimes they let their guard down (when within the confines of the authority/belief). Other times, they keep their guard up to ensure that others do not take advantage of them.",
//                             "Reactive8": "People whose dominant Harmonic approach is 'Reactive' are emotionally reactive under stress. This type can get into conflict by being too willful, defiant and confrontational. This type tends to not censor their own impulses or emotional reactions. This type wants to feel the realness of conflict to give themselves a stronger sense of being. When conflicts occur, this type is very quick to challenge and confront them. This type keep their guard up all the time and want to minimize their dependence on (and trust in) others. They do not want others to see their vulnerable side.",
//                             "Attachment3": "People with the attachment object relation tend to have a sense of contentment that their needs (with people, situations, thoughts) are being met. This type adapts their self-image to be consistent with the expectations and values of others. This type is aware of what is valued by their friends, family, coworkers, etc. and they strive to attain those values. That way, they can receive the attention and validation from others. Their sense of self is based on an attachment to their self-image of a successful, valuable person.",
//                             "Attachment6": "People with the attachment object relation tend to have a sense of contentment that their needs (with people, situations, thoughts) are being met. This type adapts their belief systems to be consistent with those of an authority figure or system. This type doubt their own ability to cope with the world, so they seek security through another person or system. Their sense of self is based on an attachment or association and loyalty to important people or groups.",
//                             "Attachment9": "People with the attachment object relation tend to have a sense of contentment that their needs (with people, situations, thoughts) are being met. This type adapts (or accommodates) their own wants and opinions to be consistent with those of others. This type want peace, so why rock the boat? By going along with others, they can attain the harmony they seek. This type bases their sense of self on their attachment to their idealized (internalized harmonious) view of the world.",
//                             "Frustration1": "People with the frustration object relation know what will make them happy, but they feel they seldom have it. This type is searching for ideal autonomy. That means perfection and complete self-control. This type focuses on what's wrong or out of place in a given situation. They become frustrated when they see that things don't live up to their standards and when they feel obligated to improve everything. Their sense of self is based on this frustration - it shows that they still care about making things better.",
//                             "Frustration4": "People with the frustration object relation know what will make them happy, but they feel they seldom have it. This type is searching for ideal attention -- a partner who completely understands and appreciates them. This type focuses on what's missing in others and in themselves. Despite their longing for an ideal partner, their actual partner has flaws and isn't quite what this type is looking for. This type seeks validation and attention from others, but feel they must be different and distant from others to get it. As a result, their strategy for attention doesn't often work, leading to a sense of frustration that maintains their sense of self.",
//                             "Frustration7": "People with the frustration object relation know what will make them happy, but they feel they seldom have it. This type is searching for ideal security and contentment. This type focuses on the fun they are not having. The current experience isn't quite as fun as they hoped it would be. Their mind quickly jumps to opportunities and experiences that they could be having rather than the one they are currently experiencing. This type gets frustrated with the present and seek security in the future. Their sense of self is based on the search rather than on the experience.",
//                             "Rejection2": "People with the rejection object relation feel that they have been rejected by others. Consequently, their relationships often have issues of not wanting to be nurtured or touched. This type rejects their own needs, their own negative thoughts and emotions. This type offers the only gift she has left: her heart. They focuses on the needs of others and helping, caring, and nurturing them. This type tries to love others so much that others won't reject them. This type bases their sense of self on putting their own needs aside (rejection) and caring for others.",
//                             "Rejection5": "People with the rejection object relation feel that they have been rejected by others. This type rejects and minimizes their own needs (especially their physical and emotional ones). This type has only one gift left: their head. This type offers their intelligence and expertise to others, hoping that others will appreciate their knowledge. By building up their own expertise, This type seeks to become important enough not to be rejected further. This type, having cut off their emotional needs, try to not need others, to be independent, and to not need love. This type believes that their lack of emotion will shield them from the pain of further rejection.",
//                             "Rejection8": "People with the rejection object relation feel that they have been rejected by others. This type rejects their own needs (especially their emotional, vulnerable side). This type only has one gift left to prevent further rejection: her strength and will. This type believes in their power and know that others can turn to them from strength and leadership. This type expects to be rejected, but because they are so 'tough,' they give the appearance of being able to handle it.",
//                         };